### ISSUE TITLE
Investigate user story mapping tools

### ISSUE THREAD

**Issue by hannesnisula** [hannesnisula/ducklib#9]
Expensive AF. StoriesOnBoard seems awesome but costs $26-33/month.

Take a look at some free ones:
- [x] **cardboardit.com**
Is it probably the best alternative out of these three. Although it has no tagging/annotations, columns are not automatically moved as a unit and the lines to split releases/backbone must be manually created and moved.
- [x] **featuremap.co**
Not really that visually clear as the others.
- [x] **miro.com**
It's like a tool within a tool. Not really that nice.

**Comment by jpsear** [comment]
Bit random, but we have a story mapping tool that might be worth checking out: https://www.avion.io

No worries if you’ve already chosen!

Hit me up if you’re wanting a startup plan

Good luck with the project 👍🏼
